package kurlyk.view.common.stage;

public enum Stages {
    COMPUTER_SYSTEM,
    CHARACTERISTIC,
    FORMULA,
    TEXT,
    NUMBER,
    MATCHING,
    CHECK,
    RADIO,

    SIGN_IN,
    START,
//    COMMON_CREATE,
    IMPORT_QUESTION,
    REGISTER,

    CREATE_LAB_WORK,
    LAB_WORK_TASK_MATCHING,
    TASK_LIST,

    CREATE_TASK,
    TASK_QUESTION_MATCHING,
    QUESTION_LIST,

    CREATE_QUESTION,
//    PERFORM_TEST,
//    PERFORM_LAB,
    PERFORM_WORK,

    LTQ_CREATE,
    EDIT_QUESTION
}
